version: 2.1

jobs:
  semgrep-scan:
    parameters:
      repo_path:
        type: string
        default: aflorithmic/apiaudio-python
      semgrep_deployment_id:
        type: integer
        default: 283
    environment:
      SEMGREP_REPO_NAME: << parameters.repo_path >>
      SEMGREP_REPO_URL: << pipeline.project.git_url >>
      SEMGREP_BRANCH: << pipeline.git.branch >>
    docker:
      - image: returntocorp/semgrep-agent:v1
    steps:
      - checkout
      - run:
          name: "Semgrep scan"
          command: |
            python -m semgrep_agent \
              --publish-deployment << parameters.semgrep_deployment_id >> \
              --publish-token $SEMGREP_APP_TOKEN



workflows:
  semgrep-scan:
    jobs:
      - semgrep-scan:
          context: aws
